export const CANDIDATE_STATUS_OPTIONS = [
  'New',
  'Contacted',
  'Interested',
  'Selected for Call',
  'Screening',
  'Interview Scheduled',
  'Selected',
  'Rejected',
  'Eligible Candidates',
  'Wrong Number',
  'Unreachable',
  'Did Not Pick',
  'Unanswered Calls',
  'Call Back',
  'HR Shortlist',
  'Written Test',
  'Operations Round',
  'Document Pending',
  'Documentation',
  'Yet To Join',
  'Joined',
  'Exited',
] as const;

export type CandidateStatus = typeof CANDIDATE_STATUS_OPTIONS[number];

export const CANDIDATE_STATUS_COLORS: Record<string, string> = {
  New: 'bg-slate-100 text-slate-600 border-slate-200',
  Contacted: 'bg-green-100 text-green-700 border-green-200',
  Interested: 'bg-emerald-100 text-emerald-700 border-emerald-200',
  'Selected for Call': 'bg-cyan-100 text-cyan-700 border-cyan-200',
  Screening: 'bg-indigo-100 text-indigo-700 border-indigo-200',
  'Interview Scheduled': 'bg-violet-100 text-violet-700 border-violet-200',
  Selected: 'bg-teal-100 text-teal-700 border-teal-200',
  Rejected: 'bg-red-100 text-red-600 border-red-200',
  'Eligible Candidates': 'bg-emerald-100 text-emerald-700 border-emerald-200',
  'Wrong Number': 'bg-orange-100 text-orange-700 border-orange-200',
  Unreachable: 'bg-orange-100 text-orange-700 border-orange-200',
  'Did Not Pick': 'bg-amber-100 text-amber-700 border-amber-200',
  'Unanswered Calls': 'bg-amber-100 text-amber-700 border-amber-200',
  'Call Back': 'bg-yellow-100 text-yellow-700 border-yellow-200',
  'HR Shortlist': 'bg-purple-100 text-purple-700 border-purple-200',
  'Written Test': 'bg-blue-100 text-blue-700 border-blue-200',
  'Operations Round': 'bg-sky-100 text-sky-700 border-sky-200',
  'Document Pending': 'bg-rose-100 text-rose-700 border-rose-200',
  Documentation: 'bg-rose-100 text-rose-700 border-rose-200',
  'Yet To Join': 'bg-purple-100 text-purple-700 border-purple-200',
  Joined: 'bg-emerald-100 text-emerald-700 border-emerald-200',
  Exited: 'bg-red-100 text-red-700 border-red-200',
};
